<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="imu_length" value="0.05" />
    <xacro:property name="imu_width" value="0.02" />
    <xacro:property name="imu_height" value="0.01" />

    <link name="imu_link">
        <visual>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" l="${imu_length}" w="${imu_width}" h="${imu_height}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="${(base_length - imu_length) / 2.0} 0 ${(base_height + (imu_height) / 2.0)}" rpy="0 0 0" />
    </joint>

    <!-- <gazebo reference="imu_link">
        <gravity>true</gravity>
        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize> -->
            <!-- <plugin name="imu" filename="libgazebo_ros_imu_sensor.so"> -->
                <!-- <topicName>robot/imu</topicName>
                <bodyName>imu_link</bodyName>
                <updateRateHZ>10.0</updateRateHZ>
                <gaussianNoise>0.0</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset> -->
                <!-- <frameName>imu_link</frameName> -->
                <!-- <initialOrientationAsReference>false</initialOrientationAsReference> -->
            <!-- </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo> -->

    <gazebo reference="imu_link">
        <gravity>true</gravity>
        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize>
            <topic>imu</topic>
            <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
                <ros>
                    <namespace>/robot</namespace>
                    <remapping>~/out:=imu</remapping>
                </ros>
                <frame_name>imu_link</frame_name>
                <initial_orientation_as_reference>false</initial_orientation_as_reference>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>

</robot>
